//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;
using MockConsultDeposit;
using www.sugiro.net;

[assembly: ContractNamespace("http://www.sugiro.net/", ClrNamespace="www.sugiro.net")]

namespace MockConsultDeposit
{
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MockConsultDeposit")]
    public partial class CompositeType : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [DataMember()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}
namespace www.sugiro.net
{
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ConsultDepositRequestBody", Namespace="http://www.sugiro.net/")]
    public partial class ConsultDepositRequestBody : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string IdTranField;
        
        private string RequestIdField;
        
        private string InqDateField;
        
        private string UserIdField;
        
        private string AgreementIdSenderField;
        
        private string AgreementIdReceiverField;
        
        private string OfficeIdField;
        
        private FinancialDataRq FinancialDataField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string IdTran
        {
            get
            {
                return this.IdTranField;
            }
            set
            {
                this.IdTranField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string InqDate
        {
            get
            {
                return this.InqDateField;
            }
            set
            {
                this.InqDateField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string AgreementIdSender
        {
            get
            {
                return this.AgreementIdSenderField;
            }
            set
            {
                this.AgreementIdSenderField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public string AgreementIdReceiver
        {
            get
            {
                return this.AgreementIdReceiverField;
            }
            set
            {
                this.AgreementIdReceiverField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public string OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public FinancialDataRq FinancialData
        {
            get
            {
                return this.FinancialDataField;
            }
            set
            {
                this.FinancialDataField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="FinancialDataRq", Namespace="http://www.sugiro.net/")]
    public partial class FinancialDataRq : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string ReferenceIdField;
        
        private string OwnerIdTypeField;
        
        private string OwnerIdField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false)]
        public string ReferenceId
        {
            get
            {
                return this.ReferenceIdField;
            }
            set
            {
                this.ReferenceIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string OwnerIdType
        {
            get
            {
                return this.OwnerIdTypeField;
            }
            set
            {
                this.OwnerIdTypeField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ConsultDepositResponseBody", Namespace="http://www.sugiro.net/")]
    public partial class ConsultDepositResponseBody : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string IdTranField;
        
        private string RequestIdField;
        
        private string InqDateField;
        
        private string UserIdField;
        
        private string AgreementIdSenderField;
        
        private string AgreementIdReceiverField;
        
        private string OfficeIdField;
        
        private FinancialDataRs FinancialDataField;
        
        private string StatusField;
        
        private string MessageField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string IdTran
        {
            get
            {
                return this.IdTranField;
            }
            set
            {
                this.IdTranField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string InqDate
        {
            get
            {
                return this.InqDateField;
            }
            set
            {
                this.InqDateField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string AgreementIdSender
        {
            get
            {
                return this.AgreementIdSenderField;
            }
            set
            {
                this.AgreementIdSenderField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public string AgreementIdReceiver
        {
            get
            {
                return this.AgreementIdReceiverField;
            }
            set
            {
                this.AgreementIdReceiverField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public string OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public FinancialDataRs FinancialData
        {
            get
            {
                return this.FinancialDataField;
            }
            set
            {
                this.FinancialDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=8)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=9)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="FinancialDataRs", Namespace="http://www.sugiro.net/")]
    public partial class FinancialDataRs : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string ReferenceIdField;
        
        private string ReferenceStatusField;
        
        private string OwnerIdTypeField;
        
        private string OwnerIdField;
        
        private string OwnerName1Field;
        
        private string OwnerName2Field;
        
        private string OwnerLastName1Field;
        
        private string OwnerLastName2Field;
        
        private AgreementData AgreementDataField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string ReferenceId
        {
            get
            {
                return this.ReferenceIdField;
            }
            set
            {
                this.ReferenceIdField = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false)]
        public string ReferenceStatus
        {
            get
            {
                return this.ReferenceStatusField;
            }
            set
            {
                this.ReferenceStatusField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string OwnerIdType
        {
            get
            {
                return this.OwnerIdTypeField;
            }
            set
            {
                this.OwnerIdTypeField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string OwnerName1
        {
            get
            {
                return this.OwnerName1Field;
            }
            set
            {
                this.OwnerName1Field = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public string OwnerName2
        {
            get
            {
                return this.OwnerName2Field;
            }
            set
            {
                this.OwnerName2Field = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public string OwnerLastName1
        {
            get
            {
                return this.OwnerLastName1Field;
            }
            set
            {
                this.OwnerLastName1Field = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public string OwnerLastName2
        {
            get
            {
                return this.OwnerLastName2Field;
            }
            set
            {
                this.OwnerLastName2Field = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public AgreementData AgreementData
        {
            get
            {
                return this.AgreementDataField;
            }
            set
            {
                this.AgreementDataField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="AgreementData", Namespace="http://www.sugiro.net/")]
    public partial class AgreementData : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string ShortNameField;
        
        private string DescriptionField;
        
        private AgreementOffice AgreementOfficeField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public AgreementOffice AgreementOffice
        {
            get
            {
                return this.AgreementOfficeField;
            }
            set
            {
                this.AgreementOfficeField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="AgreementOffice", Namespace="http://www.sugiro.net/")]
    public partial class AgreementOffice : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string ShortNameField;
        
        private string DescriptionField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
}


[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[ServiceContract(ConfigurationName="IService1")]
public interface IService1
{
    
    [OperationContract(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    string GetData(int value);
    
    [OperationContract(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    Task<string> GetDataAsync(int value);
    
    [OperationContract(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    CompositeType GetDataUsingDataContract(CompositeType composite);
    
    [OperationContract(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConsultDeposit no es RPC ni está encapsulada en un documento.
    [OperationContract(Action="http://tempuri.org/IService1/ConsultDeposit", ReplyAction="http://tempuri.org/IService1/ConsultDepositResponse")]
    ConsultDepositResponse ConsultDeposit(ConsultDepositRequest request);
    
    [OperationContract(Action="http://tempuri.org/IService1/ConsultDeposit", ReplyAction="http://tempuri.org/IService1/ConsultDepositResponse")]
    Task<ConsultDepositResponse> ConsultDepositAsync(ConsultDepositRequest request);
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Advanced)]
[MessageContract(IsWrapped=false)]
public partial class ConsultDepositRequest
{
    
    [MessageBodyMember(Namespace="http://www.sugiro.net/", Order=0)]
    public ConsultDepositRequestBody ConsultDepositRq;
    
    public ConsultDepositRequest()
    {
    }
    
    public ConsultDepositRequest(ConsultDepositRequestBody ConsultDepositRq)
    {
        this.ConsultDepositRq = ConsultDepositRq;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Advanced)]
[MessageContract(IsWrapped=false)]
public partial class ConsultDepositResponse
{
    
    [MessageBodyMember(Namespace="http://www.sugiro.net/", Order=0)]
    public ConsultDepositResponseBody ConsultDepositRs;
    
    public ConsultDepositResponse()
    {
    }
    
    public ConsultDepositResponse(ConsultDepositResponseBody ConsultDepositRs)
    {
        this.ConsultDepositRs = ConsultDepositRs;
    }
}

[GeneratedCode("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, IClientChannel
{
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(Binding binding, EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }
    
    public CompositeType GetDataUsingDataContract(CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
    
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    ConsultDepositResponse IService1.ConsultDeposit(ConsultDepositRequest request)
    {
        return base.Channel.ConsultDeposit(request);
    }
    
    public ConsultDepositResponseBody ConsultDeposit(ConsultDepositRequestBody ConsultDepositRq)
    {
        ConsultDepositRequest inValue = new ConsultDepositRequest();
        inValue.ConsultDepositRq = ConsultDepositRq;
        ConsultDepositResponse retVal = ((IService1)(this)).ConsultDeposit(inValue);
        return retVal.ConsultDepositRs;
    }
    
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    Task<ConsultDepositResponse> IService1.ConsultDepositAsync(ConsultDepositRequest request)
    {
        return base.Channel.ConsultDepositAsync(request);
    }
    
    public Task<ConsultDepositResponse> ConsultDepositAsync(ConsultDepositRequestBody ConsultDepositRq)
    {
        ConsultDepositRequest inValue = new ConsultDepositRequest();
        inValue.ConsultDepositRq = ConsultDepositRq;
        return ((IService1)(this)).ConsultDepositAsync(inValue);
    }
}
