//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace WebApplication.ServRefHello {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(Namespace="http://www.examples.com/wsdl/HelloService.wsdl", ConfigurationName="ServRefHello.Hello_PortType")]
    public interface Hello_PortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:examples:helloservice) del mensaje sayHelloRequest no coincide con el valor predeterminado (http://www.examples.com/wsdl/HelloService.wsdl)
        [OperationContract(Action="sayHello", ReplyAction="*")]
        [XmlSerializerFormat(Style=OperationFormatStyle.Rpc, SupportFaults=true, Use=OperationFormatUse.Encoded)]
        sayHelloResponse sayHello(sayHelloRequest request);
        
        [OperationContract(Action="sayHello", ReplyAction="*")]
        Task<sayHelloResponse> sayHelloAsync(sayHelloRequest request);
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="sayHello", WrapperNamespace="urn:examples:helloservice", IsWrapped=true)]
    public partial class sayHelloRequest {
        
        [MessageBodyMember(Namespace="", Order=0)]
        public string firstName;
        
        public sayHelloRequest() {
        }
        
        public sayHelloRequest(string firstName) {
            this.firstName = firstName;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="sayHelloResponse", WrapperNamespace="urn:examples:helloservice", IsWrapped=true)]
    public partial class sayHelloResponse {
        
        [MessageBodyMember(Namespace="", Order=0)]
        public string greeting;
        
        public sayHelloResponse() {
        }
        
        public sayHelloResponse(string greeting) {
            this.greeting = greeting;
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface Hello_PortTypeChannel : Hello_PortType, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class Hello_PortTypeClient : ClientBase<Hello_PortType>, Hello_PortType {
        
        public Hello_PortTypeClient() {
        }
        
        public Hello_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Hello_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hello_PortTypeClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Hello_PortTypeClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        sayHelloResponse Hello_PortType.sayHello(sayHelloRequest request) {
            return base.Channel.sayHello(request);
        }
        
        public string sayHello(string firstName) {
            sayHelloRequest inValue = new sayHelloRequest();
            inValue.firstName = firstName;
            sayHelloResponse retVal = ((Hello_PortType)(this)).sayHello(inValue);
            return retVal.greeting;
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<sayHelloResponse> Hello_PortType.sayHelloAsync(sayHelloRequest request) {
            return base.Channel.sayHelloAsync(request);
        }
        
        public Task<sayHelloResponse> sayHelloAsync(string firstName) {
            sayHelloRequest inValue = new sayHelloRequest();
            inValue.firstName = firstName;
            return ((Hello_PortType)(this)).sayHelloAsync(inValue);
        }
    }
}
