//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;
using www.sugiro.net;

[assembly: ContractNamespace("http://www.sugiro.net/", ClrNamespace="www.sugiro.net")]

namespace www.sugiro.net
{
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="FinancialDataRq", Namespace="http://www.sugiro.net/")]
    public partial class FinancialDataRq : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string ReferenceIdField;
        
        private string OwnerIdTypeField;
        
        private string OwnerIdField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false)]
        public string ReferenceId
        {
            get
            {
                return this.ReferenceIdField;
            }
            set
            {
                this.ReferenceIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string OwnerIdType
        {
            get
            {
                return this.OwnerIdTypeField;
            }
            set
            {
                this.OwnerIdTypeField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="FinancialDataRs", Namespace="http://www.sugiro.net/")]
    public partial class FinancialDataRs : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string ReferenceIdField;
        
        private string ReferenceStatusField;
        
        private string OwnerIdTypeField;
        
        private string OwnerIdField;
        
        private string OwnerName1Field;
        
        private string OwnerName2Field;
        
        private string OwnerLastName1Field;
        
        private string OwnerLastName2Field;
        
        private AgreementData AgreementDataField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string ReferenceId
        {
            get
            {
                return this.ReferenceIdField;
            }
            set
            {
                this.ReferenceIdField = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false)]
        public string ReferenceStatus
        {
            get
            {
                return this.ReferenceStatusField;
            }
            set
            {
                this.ReferenceStatusField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string OwnerIdType
        {
            get
            {
                return this.OwnerIdTypeField;
            }
            set
            {
                this.OwnerIdTypeField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string OwnerName1
        {
            get
            {
                return this.OwnerName1Field;
            }
            set
            {
                this.OwnerName1Field = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public string OwnerName2
        {
            get
            {
                return this.OwnerName2Field;
            }
            set
            {
                this.OwnerName2Field = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public string OwnerLastName1
        {
            get
            {
                return this.OwnerLastName1Field;
            }
            set
            {
                this.OwnerLastName1Field = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public string OwnerLastName2
        {
            get
            {
                return this.OwnerLastName2Field;
            }
            set
            {
                this.OwnerLastName2Field = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public AgreementData AgreementData
        {
            get
            {
                return this.AgreementDataField;
            }
            set
            {
                this.AgreementDataField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="AgreementData", Namespace="http://www.sugiro.net/")]
    public partial class AgreementData : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string ShortNameField;
        
        private string DescriptionField;
        
        private AgreementOffice AgreementOfficeField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [DataMember(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public AgreementOffice AgreementOffice
        {
            get
            {
                return this.AgreementOfficeField;
            }
            set
            {
                this.AgreementOfficeField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="AgreementOffice", Namespace="http://www.sugiro.net/")]
    public partial class AgreementOffice : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string ShortNameField;
        
        private string DescriptionField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
}


[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[ServiceContract(Namespace="http://www.sugiro.net/ConsultaMonto.ws", ConfigurationName="ConsultDepositPort")]
public interface ConsultDepositPort
{
    
    [OperationContract(Action="http://www.sugiro.net/ConsultDeposit", ReplyAction="*")]
    ConsultDepositResponse ConsultDeposit(ConsultDepositRequest request);
    
    [OperationContract(Action="http://www.sugiro.net/ConsultDeposit", ReplyAction="*")]
    Task<ConsultDepositResponse> ConsultDepositAsync(ConsultDepositRequest request);
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped=false)]
public partial class ConsultDepositRequest
{
    
    [MessageBodyMember(Name="ConsultDepositRq", Namespace="http://www.sugiro.net/", Order=0)]
    public ConsultDepositRequestBody Body;
    
    public ConsultDepositRequest()
    {
    }
    
    public ConsultDepositRequest(ConsultDepositRequestBody Body)
    {
        this.Body = Body;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[DataContract(Namespace="http://www.sugiro.net/")]
public partial class ConsultDepositRequestBody
{
    
    [DataMember(EmitDefaultValue=false, Order=0)]
    public string IdTran;
    
    [DataMember(EmitDefaultValue=false, Order=1)]
    public string RequestId;
    
    [DataMember(EmitDefaultValue=false, Order=2)]
    public string InqDate;
    
    [DataMember(EmitDefaultValue=false, Order=3)]
    public string UserId;
    
    [DataMember(EmitDefaultValue=false, Order=4)]
    public string AgreementIdSender;
    
    [DataMember(EmitDefaultValue=false, Order=5)]
    public string AgreementIdReceiver;
    
    [DataMember(EmitDefaultValue=false, Order=6)]
    public string OfficeId;
    
    [DataMember(EmitDefaultValue=false, Order=7)]
    public FinancialDataRq FinancialData;
    
    public ConsultDepositRequestBody()
    {
    }
    
    public ConsultDepositRequestBody(string IdTran, string RequestId, string InqDate, string UserId, string AgreementIdSender, string AgreementIdReceiver, string OfficeId, FinancialDataRq FinancialData)
    {
        this.IdTran = IdTran;
        this.RequestId = RequestId;
        this.InqDate = InqDate;
        this.UserId = UserId;
        this.AgreementIdSender = AgreementIdSender;
        this.AgreementIdReceiver = AgreementIdReceiver;
        this.OfficeId = OfficeId;
        this.FinancialData = FinancialData;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[MessageContract(IsWrapped=false)]
public partial class ConsultDepositResponse
{
    
    [MessageBodyMember(Name="ConsultDepositRs", Namespace="http://www.sugiro.net/", Order=0)]
    public ConsultDepositResponseBody Body;
    
    public ConsultDepositResponse()
    {
    }
    
    public ConsultDepositResponse(ConsultDepositResponseBody Body)
    {
        this.Body = Body;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
[DataContract(Namespace="http://www.sugiro.net/")]
public partial class ConsultDepositResponseBody
{
    
    [DataMember(EmitDefaultValue=false, Order=0)]
    public string IdTran;
    
    [DataMember(EmitDefaultValue=false, Order=1)]
    public string RequestId;
    
    [DataMember(EmitDefaultValue=false, Order=2)]
    public string InqDate;
    
    [DataMember(EmitDefaultValue=false, Order=3)]
    public string UserId;
    
    [DataMember(EmitDefaultValue=false, Order=4)]
    public string AgreementIdSender;
    
    [DataMember(EmitDefaultValue=false, Order=5)]
    public string AgreementIdReceiver;
    
    [DataMember(EmitDefaultValue=false, Order=6)]
    public string OfficeId;
    
    [DataMember(EmitDefaultValue=false, Order=7)]
    public FinancialDataRs FinancialData;
    
    [DataMember(EmitDefaultValue=false, Order=8)]
    public string Status;
    
    [DataMember(EmitDefaultValue=false, Order=9)]
    public string Message;
    
    public ConsultDepositResponseBody()
    {
    }
    
    public ConsultDepositResponseBody(string IdTran, string RequestId, string InqDate, string UserId, string AgreementIdSender, string AgreementIdReceiver, string OfficeId, FinancialDataRs FinancialData, string Status, string Message)
    {
        this.IdTran = IdTran;
        this.RequestId = RequestId;
        this.InqDate = InqDate;
        this.UserId = UserId;
        this.AgreementIdSender = AgreementIdSender;
        this.AgreementIdReceiver = AgreementIdReceiver;
        this.OfficeId = OfficeId;
        this.FinancialData = FinancialData;
        this.Status = Status;
        this.Message = Message;
    }
}

[GeneratedCode("System.ServiceModel", "4.0.0.0")]
public interface ConsultDepositPortChannel : ConsultDepositPort, IClientChannel
{
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "4.0.0.0")]
public partial class ConsultDepositPortClient : ClientBase<ConsultDepositPort>, ConsultDepositPort
{
    
    public ConsultDepositPortClient()
    {
    }
    
    public ConsultDepositPortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ConsultDepositPortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConsultDepositPortClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConsultDepositPortClient(Binding binding, EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ConsultDepositResponse ConsultDeposit(ConsultDepositRequest request)
    {
        return base.Channel.ConsultDeposit(request);
    }
    
    public Task<ConsultDepositResponse> ConsultDepositAsync(ConsultDepositRequest request)
    {
        return base.Channel.ConsultDepositAsync(request);
    }
}
