//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public decimal nitcliente { get; set; }
        public string cliendigito { get; set; }
        public string nombrecliente { get; set; }
        public Nullable<int> ciudadprincipal { get; set; }
        public string direccionempresa { get; set; }
        public decimal cedulareplegal { get; set; }
        public string nombrerepresentante { get; set; }
        public string telefonorepresentante { get; set; }
        public string exttelrepresentante { get; set; }
        public string telefonofaxc { get; set; }
        public string exttelfaxc { get; set; }
        public short diafacturacion { get; set; }
        public short diacompago { get; set; }
        public string codigopriciiu { get; set; }
        public string codpromotora { get; set; }
        public string codigousuario { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public string codigomodificacion { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<short> tipocartera { get; set; }
        public string tipodocumento { get; set; }
        public Nullable<bool> manejoweb { get; set; }
        public string formatounafactura { get; set; }
        public Nullable<short> unafacturacli { get; set; }
        public string sectorunafactura { get; set; }
        public Nullable<short> exigenominafact { get; set; }
        public Nullable<short> diasmora { get; set; }
    }
}
