//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class concepto_contable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public concepto_contable()
        {
            this.movimiento_concepto = new HashSet<movimiento_concepto>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_compania_nomina { get; set; }
        public Nullable<int> id_compania_pago { get; set; }
        public string usu_creacion { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public string usu_modificacion { get; set; }
        public Nullable<System.DateTime> fec_modificacion { get; set; }
        public Nullable<decimal> estado { get; set; }
        public Nullable<short> aplica_rechazo { get; set; }
    
        public virtual compania compania { get; set; }
        public virtual compania compania1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_concepto> movimiento_concepto { get; set; }
    }
}
