//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        public short contraempresa { get; set; }
        public short contrasucursal { get; set; }
        public short contraanio { get; set; }
        public int contrasecue { get; set; }
        public Nullable<System.DateTime> fechacontrato { get; set; }
        public Nullable<short> consecutivoanio { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public Nullable<decimal> nitcliente { get; set; }
        public string codsector { get; set; }
        public Nullable<decimal> docutrabajador { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> fechafinal { get; set; }
        public string estadocontrato { get; set; }
        public string codigocargo { get; set; }
        public decimal salario { get; set; }
        public Nullable<short> horaslaborables { get; set; }
        public Nullable<short> tiponomina { get; set; }
        public Nullable<decimal> tarifaatep { get; set; }
        public string cencostoclie { get; set; }
        public string cencontaclie { get; set; }
        public Nullable<int> ciudadlaboral { get; set; }
        public string codigousuario { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public string usuariomod { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
        public Nullable<bool> fasenomina { get; set; }
        public Nullable<bool> conseguridad { get; set; }
        public Nullable<bool> concuebancos { get; set; }
        public Nullable<bool> condocumentos { get; set; }
        public Nullable<bool> conparientes { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<bool> traslado { get; set; }
        public Nullable<short> codigosucursal { get; set; }
        public Nullable<short> consecutivomov { get; set; }
        public string sumaconsecutivos { get; set; }
        public Nullable<short> division { get; set; }
        public Nullable<short> sena { get; set; }
        public Nullable<decimal> baseretencion { get; set; }
        public Nullable<short> borrar { get; set; }
        public Nullable<decimal> salario1 { get; set; }
        public Nullable<System.DateTime> progretiro { get; set; }
        public Nullable<short> decalarafuente { get; set; }
        public Nullable<decimal> transporte { get; set; }
        public Nullable<decimal> comunicacion { get; set; }
        public Nullable<decimal> alimentacion { get; set; }
        public string codigocentrocosto { get; set; }
        public Nullable<short> causervi { get; set; }
        public Nullable<int> concoanio { get; set; }
        public string concosecue { get; set; }
        public string grupocosto { get; set; }
        public string cencosto { get; set; }
        public string regional { get; set; }
        public Nullable<short> tipocontrato { get; set; }
        public Nullable<short> codigogrupo { get; set; }
        public Nullable<short> codigoservicio { get; set; }
        public Nullable<short> perfil { get; set; }
        public Nullable<short> ubicasaludp { get; set; }
        public string div472 { get; set; }
        public string descripcionbloqueo { get; set; }
        public Nullable<short> tipocontrato1 { get; set; }
        public string centrocosto3 { get; set; }
        public string numeronovedad { get; set; }
        public string sban { get; set; }
    }
}
