//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctaempleado
    {
        public short contraempresa { get; set; }
        public short contrasucursal { get; set; }
        public short contraanio { get; set; }
        public int contrasecue { get; set; }
        public string codbanco { get; set; }
        public string codsucursal { get; set; }
        public string cuentaempleado { get; set; }
        public string tipocuenta { get; set; }
        public System.DateTime fechainicio { get; set; }
        public Nullable<System.DateTime> fechafinal { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public string codigousuario { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public string usuariomod { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
    }
}
