//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta_compania
    {
        public int id_cuenta_compania { get; set; }
        public string num_cuenta { get; set; }
        public int id_compania { get; set; }
        public string cod_banco { get; set; }
        public string nom_banco { get; set; }
        public Nullable<int> id_tipo_cuenta { get; set; }
        public string usu_creacion { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public string usu_modificacion { get; set; }
        public Nullable<System.DateTime> fec_modificacion { get; set; }
        public short estado { get; set; }
        public Nullable<int> cod_contable { get; set; }
    
        public virtual compania compania { get; set; }
        public virtual tipo_cuenta tipo_cuenta { get; set; }
    }
}
