//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresasp
    {
        public short codigoempresa { get; set; }
        public string nombreempresa { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<decimal> nitempresa { get; set; }
        public Nullable<short> dvempresa { get; set; }
        public string direccionempresa { get; set; }
        public string arpsoiempresa { get; set; }
        public string direccionsucursal { get; set; }
    }
}
