//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbserviproductoEntities : DbContext
    {
        public dbserviproductoEntities()
            : base("name=dbserviproductoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ad_regionales> ad_regionales { get; set; }
        public virtual DbSet<archivo> archivo { get; set; }
        public virtual DbSet<archivo_body> archivo_body { get; set; }
        public virtual DbSet<archivo_body_dominio> archivo_body_dominio { get; set; }
        public virtual DbSet<archivo_footer> archivo_footer { get; set; }
        public virtual DbSet<archivo_head> archivo_head { get; set; }
        public virtual DbSet<archivo_head_dominio> archivo_head_dominio { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<codigo_contable> codigo_contable { get; set; }
        public virtual DbSet<compania> compania { get; set; }
        public virtual DbSet<concepto_contable> concepto_contable { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<ctaempleado> ctaempleado { get; set; }
        public virtual DbSet<cuenta_compania> cuenta_compania { get; set; }
        public virtual DbSet<empresasp> empresasp { get; set; }
        public virtual DbSet<movimiento_concepto> movimiento_concepto { get; set; }
        public virtual DbSet<movimiento_contable> movimiento_contable { get; set; }
        public virtual DbSet<n_consecutivosiesa> n_consecutivosiesa { get; set; }
        public virtual DbSet<n_movimientocabecera> n_movimientocabecera { get; set; }
        public virtual DbSet<n_tiponomina> n_tiponomina { get; set; }
        public virtual DbSet<nomina> nomina { get; set; }
        public virtual DbSet<nomina_rechazada> nomina_rechazada { get; set; }
        public virtual DbSet<p_cliente_bloqueado> p_cliente_bloqueado { get; set; }
        public virtual DbSet<p_colaborador_bloqueado> p_colaborador_bloqueado { get; set; }
        public virtual DbSet<p_formato_respuesta_banco> p_formato_respuesta_banco { get; set; }
        public virtual DbSet<p_motivo_rechazo> p_motivo_rechazo { get; set; }
        public virtual DbSet<parametro> parametro { get; set; }
        public virtual DbSet<rechazo> rechazo { get; set; }
        public virtual DbSet<rechazo_detalle> rechazo_detalle { get; set; }
        public virtual DbSet<reclutamiento> reclutamiento { get; set; }
        public virtual DbSet<secuencias> secuencias { get; set; }
        public virtual DbSet<sucursalesp> sucursalesp { get; set; }
        public virtual DbSet<tabancos> tabancos { get; set; }
        public virtual DbSet<tabasucursal> tabasucursal { get; set; }
        public virtual DbSet<tipo_cuenta> tipo_cuenta { get; set; }
        public virtual DbSet<tipo_nomina> tipo_nomina { get; set; }
        public virtual DbSet<tipo_transaccion> tipo_transaccion { get; set; }
        public virtual DbSet<tiponomina> tiponomina { get; set; }
        public virtual DbSet<tope_contrato> tope_contrato { get; set; }
        public virtual DbSet<transaccion> transaccion { get; set; }
        public virtual DbSet<transaccion_detalle> transaccion_detalle { get; set; }
        public virtual DbSet<seg_paginas> seg_paginas { get; set; }
        public virtual DbSet<seg_permisos> seg_permisos { get; set; }
        public virtual DbSet<seg_rol> seg_rol { get; set; }
        public virtual DbSet<seg_usuarios> seg_usuarios { get; set; }
    }
}
