//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_contable
    {
        public int id { get; set; }
        public Nullable<int> id_compania { get; set; }
        public Nullable<decimal> tercero { get; set; }
        public string centro_operacion { get; set; }
        public Nullable<decimal> monto_debito { get; set; }
        public Nullable<decimal> monto_credito { get; set; }
        public string documento_cruce { get; set; }
        public string descripcion_movimiento { get; set; }
        public string usu_creacion { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public string usu_modificacion { get; set; }
        public Nullable<System.DateTime> fec_modificacion { get; set; }
        public Nullable<decimal> estado { get; set; }
        public Nullable<short> generado { get; set; }
        public string codigo_contable { get; set; }
        public Nullable<int> id_transaccion { get; set; }
        public Nullable<int> lote { get; set; }
    
        public virtual compania compania { get; set; }
    }
}
