//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_movimientocabecera
    {
        public short codempresamov { get; set; }
        public short codsucursalmov { get; set; }
        public short anocmov { get; set; }
        public int consecutivocmov { get; set; }
        public short consecmov { get; set; }
        public Nullable<System.DateTime> fechamov { get; set; }
        public Nullable<System.DateTime> fechainicialmov { get; set; }
        public Nullable<System.DateTime> fechafinalmov { get; set; }
        public Nullable<short> finmesmov { get; set; }
        public Nullable<short> programadosmov { get; set; }
        public string sufijofacturamov { get; set; }
        public Nullable<int> numerofacturamov { get; set; }
        public Nullable<decimal> valornetomov { get; set; }
        public string codbancomov { get; set; }
        public string codsucursalbanco { get; set; }
        public string cuentaempleadomov { get; set; }
        public string numernominamov { get; set; }
        public Nullable<short> estadomov { get; set; }
        public string codigousuario { get; set; }
        public Nullable<short> estadopago { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<decimal> diasserviciosc { get; set; }
        public Nullable<decimal> diasnetosc { get; set; }
        public Nullable<short> anopago { get; set; }
        public Nullable<decimal> consecutivopago { get; set; }
        public Nullable<short> tiponomi { get; set; }
        public Nullable<decimal> nominasiesa { get; set; }
        public string aplicacion { get; set; }
    }
}
