//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class reclutamiento
    {
        public string tipodocumento { get; set; }
        public decimal numerodocumento { get; set; }
        public string expedidoen { get; set; }
        public string primerapellido { get; set; }
        public string segundoapellido { get; set; }
        public string primernombre { get; set; }
        public string segundonombre { get; set; }
        public Nullable<short> codigosucursal { get; set; }
        public string sexo { get; set; }
        public string estadocivil { get; set; }
        public string estadoactual { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public Nullable<int> lugarnacimiento { get; set; }
        public Nullable<int> residencia { get; set; }
        public string direccionresidencia { get; set; }
        public string barrio { get; set; }
        public string telefonoresidencia { get; set; }
        public string telefonooficina { get; set; }
        public string telefonocelular { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fechareclutamiento { get; set; }
        public Nullable<System.DateTime> fechaproxcita { get; set; }
        public Nullable<bool> autoparticular { get; set; }
        public Nullable<bool> motoparticular { get; set; }
        public Nullable<bool> pasevehimoto { get; set; }
        public string catcondauto { get; set; }
        public string catcondmoto { get; set; }
        public Nullable<decimal> aspiracionsalarial { get; set; }
        public Nullable<short> reubicacion { get; set; }
        public Nullable<short> experiencialaboral { get; set; }
        public string codigoentrevistador { get; set; }
        public string codigosicologo { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public string tiposangre { get; set; }
        public Nullable<short> codhorario { get; set; }
        public Nullable<bool> libretamilitar { get; set; }
        public Nullable<short> distmilitar { get; set; }
        public Nullable<short> tipolibreta { get; set; }
        public Nullable<bool> signosangre { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public string codigomodificador { get; set; }
        public Nullable<short> numrecluanio { get; set; }
        public Nullable<int> numreclusecue { get; set; }
        public Nullable<bool> laboentrevista { get; set; }
        public Nullable<bool> cambioresidencia { get; set; }
        public Nullable<System.DateTime> fechaweb { get; set; }
        public string cabezafam { get; set; }
        public Nullable<bool> habeasdata { get; set; }
        public string usuhabeas { get; set; }
        public string nomcontacto { get; set; }
        public string telcontacto { get; set; }
        public string estadoregistro { get; set; }
        public Nullable<short> nrohijos { get; set; }
        public Nullable<System.DateTime> fechaexpedicion { get; set; }
    }
}
