//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_permisos
    {
        public int id_seg_permisos { get; set; }
        public Nullable<int> id_seg_rol { get; set; }
        public Nullable<int> id_seg_paginas { get; set; }
        public short crear { get; set; }
        public short consultar { get; set; }
        public short modificar { get; set; }
        public short inactivar { get; set; }
        public short exportar { get; set; }
        public short generar { get; set; }
        public string usu_creacion { get; set; }
        public System.DateTime fec_creacion { get; set; }
        public string usu_modificacion { get; set; }
        public Nullable<System.DateTime> fec_modificacion { get; set; }
    
        public virtual seg_paginas seg_paginas { get; set; }
        public virtual seg_rol seg_rol { get; set; }
    }
}
