//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursalesp
    {
        public short codigosucursal { get; set; }
        public string nombresucursal { get; set; }
        public string tipodocegreso { get; set; }
        public Nullable<int> tempo { get; set; }
        public string direccionsucursal { get; set; }
        public string barrio { get; set; }
        public string telefonos { get; set; }
        public string fax { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
        public string codigoregional { get; set; }
        public Nullable<bool> actsyacamcio { get; set; }
        public string syacamcio { get; set; }
        public Nullable<bool> actsecamcio { get; set; }
        public string secamcio { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaactivacion { get; set; }
        public Nullable<int> ubicacion { get; set; }
        public Nullable<short> ciuppal { get; set; }
    }
}
