//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabancos()
        {
            this.tabasucursal = new HashSet<tabasucursal>();
        }
    
        public string codbanco { get; set; }
        public string nombrebanco { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<decimal> digitos { get; set; }
        public Nullable<short> tipoplano { get; set; }
        public string codigobanco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabasucursal> tabasucursal { get; set; }
    }
}
