//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabasucursal
    {
        public string codbanco { get; set; }
        public string codsucursal { get; set; }
        public string numerocuenta { get; set; }
        public string nombresucursal { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string telefono { get; set; }
        public string exttelefono { get; set; }
        public string fax { get; set; }
        public string extfax { get; set; }
        public Nullable<short> empresacta { get; set; }
        public string archivoplano { get; set; }
        public string codrelacion { get; set; }
        public string codpagootrobco { get; set; }
        public string habilitado { get; set; }
        public string codigousuario { get; set; }
        public Nullable<System.DateTime> fechacreación { get; set; }
        public string usuariomod { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
    
        public virtual tabancos tabancos { get; set; }
    }
}
