//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiponomina
    {
        public short codtiponomina { get; set; }
        public string nomtiponomina { get; set; }
        public Nullable<short> diasnomina { get; set; }
        public Nullable<bool> habilitado { get; set; }
    }
}
