//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tope_contrato
    {
        public int id_tope_contrato { get; set; }
        public string num_contrato { get; set; }
        public Nullable<decimal> max_monto_tope { get; set; }
        public string usu_creacion { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public string usu_modificacion { get; set; }
        public Nullable<System.DateTime> fec_modificacion { get; set; }
    }
}
